### ISSUE TITLE
Wrong filename with for the Classes

### ISSUE THREAD

**Issue by khanra17** [PacktPublishing/Clean-Android-Architecture#1]
Filename should be `LocalUserDataSourceImplTest` not `RemoteUserDataSourceImplTest`
https://github.com/PacktPublishing/Clean-Android-Architecture/blob/20714181bb3ff7ea1d6993141d35aa0996a73158/Chapter7/Exercise07.02/data-local/src/test/java/com/clean/data_local/source/RemoteUserDataSourceImplTest.kt#L16

Filename should be `LocalPostDataSourceImplTest` not `RemotePostDataSourceImplTest`
https://github.com/PacktPublishing/Clean-Android-Architecture/blob/20714181bb3ff7ea1d6993141d35aa0996a73158/Chapter7/Exercise07.02/data-local/src/test/java/com/clean/data_local/source/RemotePostDataSourceImplTest.kt#L16

**Comment by alexandrudumbravan** [comment]
@khanra17 Thank you for the find. I've updated the file names to the correct ones.

**Comment by khanra17** [comment]
Thank you.
